version: "3"

services:
  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/usr/src/web
      - /usr/src/web/node_modules
    tty: true
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
